import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useTable } from "react-table";
import React from "react";

function formatTime(seconds: number) {
  return [
    Math.floor(seconds / 60), // minutes
    Math.floor(seconds % 60), // remaining seconds
  ]
    .map((x) => x.toString())

    .map((x) => (x.length === 1 ? `0${x}` : x))
    .join(":");
}

interface Props {
  tracks: never[];
  setTracks: React.Dispatch<React.SetStateAction<never[]>>;
  trackIndex: number;
  setTrackIndex: React.Dispatch<React.SetStateAction<number>>;
}

const Home: React.FC<Props> = ({
  tracks,
  setTracks,
  trackIndex,
  setTrackIndex,
}) => {
  const data = React.useMemo(
    () => [
      {
        title: "epic",
        artist: "bensound.com",
        time: 178,
        image: "/1.jpg",
        location: "./bensound-epic.mp3",
      },
      {
        title: "SciFi",
        artist: "bensound.com",
        time: 284,
        image: "/2.jpg",
        location: "./bensound-scifi.mp3",
      },
      {
        title: "Postive Effect",
        artist: "Marc Rebillet",
        time: 42,
        image: "/3.jpg",
        location: "./positiveEffect.mp3",
      },
      {
        title: "epic",
        artist: "bensound.com",
        time: 178,
        image: "/1.jpg",
        location: "./bensound-epic.mp3",
      },
      {
        title: "SciFi",
        artist: "bensound.com",
        time: 284,
        image: "/2.jpg",
        location: "./bensound-scifi.mp3",
      },
      {
        title: "Postive Effect",
        artist: "Marc Rebillet",
        time: 42,
        image: "/3.jpg",
        location: "./positiveEffect.mp3",
      },
      {
        title: "epic",
        artist: "bensound.com",
        time: 178,
        image: "/1.jpg",
        location: "./bensound-epic.mp3",
      },
      {
        title: "SciFi",
        artist: "bensound.com",
        time: 284,
        image: "/2.jpg",
        location: "./bensound-scifi.mp3",
      },
      {
        title: "Postive Effect",
        artist: "Marc Rebillet",
        time: 42,
        image: "/3.jpg",
        location: "./positiveEffect.mp3",
      },
    ],
    []
  ) as any;
  const columns = React.useMemo(
    () => [
      {
        Header: "#",
        accessor: "image",
        // eslint-disable-next-line react/display-name
        Cell: ({ cell }: any) => (
          <div className={styles.indexDiv}>
            <p className={styles.text}>{cell.row.index + 1}</p>
            <div className={styles.albumArt}>
              <Image
                src={cell.row.values.image}
                alt={`${cell.row.values.title}`}
                width={50}
                height={50}
              ></Image>
            </div>
          </div>
        ),
      },
      {
        Header: "Title",
        // eslint-disable-next-line react/display-name
        accessor: "title",
        // eslint-disable-next-line react/display-name
        Cell: ({ cell }: any) => (
          <div>
            <p className={styles.title}>{cell.row.values.title}</p>
          </div>
        ),
      },
      {
        Header: "Artist",
        accessor: "artist",
        // eslint-disable-next-line react/display-name
        Cell: ({ cell }: any) => (
          <div>
            <p className={styles.text}>{cell.row.values.artist}</p>
          </div>
        ),
      },
      {
        Header: "duration",
        accessor: "time",
        // eslint-disable-next-line react/display-name
        Cell: ({ cell }: any) => (
          <div>
            <p className={styles.text}>{formatTime(cell.row.values.time)}</p>
          </div>
        ),
      },
    ],
    []
  ) as any;
  const { getTableProps, getTableBodyProps, headerGroups, rows, prepareRow } =
    useTable({ columns, data });

  return (
    <div className={styles["main-container"]}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles["playlist-title-container"]}>
          <div className={styles["playlist-grid"]}>
            <div className={styles.playlistArt}>
              <Image src="/1.jpg" alt="playlist art" width={200} height={200} />
            </div>
            <div className={styles["playlist-info"]}>
              <h2>Playlist</h2>
              <h1>PlayList Title</h1>
              <p>description</p>
              <p>playlist info summary</p>
            </div>
          </div>
        </div>

        <div className={styles.tableContainer}>
          <table className={styles.table} {...getTableProps()}>
            <thead className={styles["table-head"]}>
              {headerGroups.map((headerGroup) => {
                const { key, ...restHeaderGroupProps } =
                  headerGroup.getHeaderGroupProps();
                return (
                  <tr
                    className={styles["header-row"]}
                    key={key}
                    {...restHeaderGroupProps}
                  >
                    {headerGroup.headers.map((column) => {
                      const { key, ...restColumn } = column.getHeaderProps();
                      return (
                        <th
                          className={styles["header"]}
                          key={key}
                          {...restColumn}
                        >
                          {column.render("Header")}
                        </th>
                      );
                    })}
                  </tr>
                );
              })}
            </thead>
            <tbody className={styles.tableBody} {...getTableBodyProps}>
              {rows.map((row, i) => {
                prepareRow(row);
                const { key, ...restRowProps } = row.getRowProps();
                return (
                  <tr
                    onDoubleClick={() => {
                      setTracks(data);
                      setTrackIndex(i);
                    }}
                    className={styles["playlist-row"]}
                    key={key}
                    {...restRowProps}
                  >
                    {row.cells.map((cell) => {
                      const { key, ...restCellProps } = cell.getCellProps();
                      return (
                        <td key={key} {...restCellProps}>
                          {cell.render("Cell")}
                        </td>
                      );
                    })}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </main>
    </div>
  );
};
export default Home;
